user_input1 = int(input("please enter a number: "))
user_input2 = int(input("please enter a number: "))
user_input3 = int(input("please enter a number: "))
user_input4 = int(input("please enter a number: "))
user_input5 = int(input("please enter a number: "))
print(user_input1 * 3)
print(user_input2 * 3)
print(user_input3 * 3)
print(user_input4 * 3)
print(user_input5 * 3)